### ISSUE TITLE
Preconstruct v2

### ISSUE THREAD

**Issue by mitchellhamilton** [preconstruct/preconstruct#331]
There are some breaking changes I've been thinking of making for a while so I'm probably gonna do a major reasonably soon.

- [x] New entrypoints - I'm quite happy with the new entrypoints, I've been using it on a bunch of repos and it's been great
  - [x] Throw an error on the case where two source files that are both configured as entrypoints would create the same entrypoint (i.e. `pkg/src/something.js` + `pkg/src/something/index.js` or `pkg/src/something.js` + `pkg/src/something.ts` or etc.)
  - [x] Tests
  - [x] Docs
- [x] New dist filenames #244 (there will be an option to use the old names so that packages that treat the dist filenames as part of their public API can update without doing a major version(basically for UMD builds))
- [x] New approach for process.env.NODE_ENV replacement + stop running Terser on the CJS prod build. I fixed process.env.NODE_ENV re-assignment causing an error because of the naive replacement by using an option in Terser to define globals but I'd like to stop running Terser on the CJS because it's not the fastest thing and Rollup does the dead code elimination anyway so it's pretty pointless so my plan is to get the Acorn AST and use magic-string to do the actual replacement(and probably do some weird things to avoid re-parsing it as well) #333
  Even though it's a really minor thing, I'd like to do it in a major(+ flag before that) just in case it breaks things
  - [ ] consider #249 with this
